# -*- coding: utf-8 -*-
"""MO_Proje

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRf7sj3afGOjT16SZZ4QN-dc8KI4DUqv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# 1. VERİ YÜKLEME
try:
    # low_memory=False ve hatalı satırlara karşı önlem
    df = pd.read_csv('Smart Home Dataset.csv', low_memory=False)
    print("Veri başarıyla yüklendi!")
except FileNotFoundError:
    print("Hata: 'Smart Home Dataset.csv' dosyası bulunamadı.")

# 2. VERİ TEMİZLEME (Hata Çözümü)
print("Zaman verileri dönüştürülüyor ve temizleniyor...")

# 'errors=coerce' hatalı değerleri (backslash gibi) NaT (boş) yapar
df['time'] = pd.to_datetime(df['time'], unit='s', errors='coerce')

# NaT (hatalı zamanlar) ve diğer boş satırları tamamen temizleyelim
initial_len = len(df)
df = df.dropna(subset=['time', 'use [kW]'])
cleaned_len = len(df)

print(f"{initial_len - cleaned_len} adet hatalı/boş satır temizlendi.")

# Zaman özelliklerini çıkaralım
df['Hour'] = df['time'].dt.hour
df['Month'] = df['time'].dt.month
df['Day'] = df['time'].dt.dayofweek

df['is_Weekend'] = df['Day'].apply(lambda x: 1 if x >= 5 else 0)

target_col = 'use [kW]'

# 3. MEVSİMSEL PIVOT (Seasonal Baseline)
# "Bu ayda ve bu saatte normal tüketim nedir?"
pivot_table = df.pivot_table(values=target_col,
                             index=['Hour', 'Month', 'is_Weekend'],
                             aggfunc='mean').reset_index()

pivot_table.rename(columns={target_col: 'Seasonal_Baseline'}, inplace=True)

# Pivot bilgisini ana tabloya ekle
df = df.merge(pivot_table, on=['Hour', 'Month'], how='left')

print("Mevsimsel Baseline eklendi.")

# 4. MODEL HAZIRLIĞI
# Önemli: 'Seasonal_Baseline' modelin en büyük yardımcısı olacak.
features = ['Hour', 'Month', 'Day', 'temperature', 'humidity', 'pressure', 'windSpeed', 'Seasonal_Baseline']
X = df[features]
y = df[target_col]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. MODEL EĞİTİMİ
print("\nModel eğitiliyor... (Bu işlem verinin büyüklüğüne göre zaman alabilir)")
# Not: Eğitim çok uzun sürerse n_estimators=20 yapabilirsin
rf_model = RandomForestRegressor(n_estimators=50, random_state=42, n_jobs=-1)
rf_model.fit(X_train, y_train)

# 6. SONUÇLAR
y_pred = rf_model.predict(X_test)

print("-" * 40)
print(f"Final R2 Skoru: {r2_score(y_test, y_pred):.4f}")
print(f"Final Hata Payı (MAE): {mean_absolute_error(y_test, y_pred):.4f} kW")
print("-" * 40)

# Özellik Önem Sıralaması
plt.figure(figsize=(10,6))
importances = pd.Series(rf_model.feature_importances_, index=features)
importances.sort_values().plot(kind='barh', color='darkgreen')
plt.title('Final Model: Özelliklerin Karara Etkisi')
plt.show()